### ISSUE TITLE
Move twitter and flickr functions to separate modules

### ISSUE THREAD

**Issue by livercat** [decobots/python-twitter-bot#14]
Example project structure:
main.py
src
-- twitter.py
-- flickr.py
tests
-- test_twitter.py
-- test_flickr.py
-- test_end_to_end.py

**Comment by livercat** [comment]
Example project structure:
main.py
src
--twitter.py
--flickr.py
tests
--test_flickr.py
--test_twitter.py
--test_end_to_end.py

**Comment by decobots** [comment]
done
